services:
  - type: web
    name: n8n
    plan: starter
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
envVars:
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - key: N8N_BASIC_AUTH_USER
    value: ""
  - key: N8N_BASIC_AUTH_PASSWORD
    value: ""
  - key: N8N_HOST
    value: ""
  - key: N8N_PORT
    value: "443"
  - key: WEBHOOK_TUNNEL_URL
    value: ""
  - key: GENERIC_TIMEZONE
    value: America/Los_Angeles
  - key: N8N_CUSTOM_EXTENSIONS
    value: /data/custom
